name: "Run go test"
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22.4'
      - 
        name: Install dependencies
        run: go get .
      - 
        name: Build
        run: go build -v ./...
      - 
        name: Test with the Go CLI
        run: LATITUDE_AUTH_TOKEN="recorded-key" LATITUDE_TEST_ACTUAL_API=true LATITUDE_TEST_RECORDER=play go test -v
